import { POPULAR_APP_IDS as POPULAR_APP_IDS_SOURCE } from './apps'

export { analyzeArchitecture } from './recommend'
export { APP_CATALOG, APP_BY_ID, APP_CATEGORY_LABELS, getApps } from './apps'
export const POPULAR_APP_IDS: readonly string[] = POPULAR_APP_IDS_SOURCE
export { inferEnvironment, getQuestionPlan } from './discovery'
export { assessDecisionStability } from './decision-stability'
export type { DecisionStability } from './decision-stability'
export { assessProcessReadiness } from './process-readiness'
export type { ProcessDisposition, ProcessReadiness } from './process-readiness'
export { recommendOperatingModel } from './operating-model'
export { PLATFORMS } from './platforms'
export { DEFAULT_ASSESSMENT, BENCHMARK_SCENARIOS } from './scenarios'
export { stressTestArchitecture } from './stress'
export type * from './apps'
export type * from './types'
