import type { AppCategory } from './apps'
import type { PlatformId, TeamProfile } from './types'

export type BillingModel = 'included-native' | 'successful-actions' | 'module-credits' | 'workflow-executions' | 'compute-credits' | 'capacity-licensing' | 'enterprise-usage' | 'self-hosted' | 'engineering'

export type PlatformProfile = {
  id: PlatformId
  name: string
  description: string
  billingModel: BillingModel
  billingLabel: string
  procurement: 'self-serve' | 'mixed' | 'enterprise' | 'engineering'
  technicalDepth: number
  technicalRequirement: number
  simpleWorkflowFit: number
  complexWorkflowFit: number
  standardIntegrationBreadth: number
  customApiFit: number
  scaleFit: number
  reliabilityFit: number
  governanceFit: number
  selfHostFit: number
  crmNativeFit: number
  microsoftFit: number
  costAtScaleFit: number
  budgetFloor: number
  teamFit: Record<TeamProfile, number>
  categoryFit: Partial<Record<AppCategory, number>>
  volumeEconomics: { light: number; moderate: number; heavy: number; 'very-heavy': number }
}

const broad = {
  crm: 92,
  marketing: 92,
  forms: 96,
  communication: 96,
  project: 94,
  finance: 88,
  commerce: 92,
  data: 82,
  developer: 74,
  support: 92,
  ads: 92,
  web: 88,
  ai: 84,
  hr: 84,
  calendar: 96,
  documents: 90,
  automation: 70,
  erp: 66,
} satisfies Partial<Record<AppCategory, number>>

export const PLATFORMS: PlatformProfile[] = [
  {
    id: 'crm-native',
    name: 'CRM-native automation',
    description: 'Keep simple lifecycle, pipeline, follow-up, and ownership logic in the CRM when it already has the capability.',
    billingModel: 'included-native',
    billingLabel: 'Usually covered by the CRM plan rather than a separate per-action automation bill.',
    procurement: 'self-serve',
    technicalDepth: 18,
    technicalRequirement: 12,
    simpleWorkflowFit: 100,
    complexWorkflowFit: 38,
    standardIntegrationBreadth: 48,
    customApiFit: 38,
    scaleFit: 70,
    reliabilityFit: 80,
    governanceFit: 78,
    selfHostFit: 0,
    crmNativeFit: 100,
    microsoftFit: 48,
    costAtScaleFit: 90,
    budgetFloor: 0,
    teamFit: { business: 100, automation: 82, developer: 56, mixed: 88 },
    categoryFit: { crm: 100, marketing: 78, forms: 70, communication: 66, ads: 62, calendar: 62, support: 58, finance: 38, data: 42, developer: 28, erp: 32 },
    volumeEconomics: { light: 98, moderate: 96, heavy: 88, 'very-heavy': 78 },
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Strong default for common SaaS handoffs when speed, connector breadth, and non-technical ownership matter more than infrastructure control.',
    billingModel: 'successful-actions',
    billingLabel: 'Usage pressure rises with successful action steps, so long or high-volume workflows deserve an economics check.',
    procurement: 'self-serve',
    technicalDepth: 32,
    technicalRequirement: 24,
    simpleWorkflowFit: 98,
    complexWorkflowFit: 62,
    standardIntegrationBreadth: 100,
    customApiFit: 68,
    scaleFit: 66,
    reliabilityFit: 76,
    governanceFit: 82,
    selfHostFit: 0,
    crmNativeFit: 70,
    microsoftFit: 72,
    costAtScaleFit: 48,
    budgetFloor: 1,
    teamFit: { business: 100, automation: 92, developer: 66, mixed: 92 },
    categoryFit: broad,
    volumeEconomics: { light: 96, moderate: 82, heavy: 58, 'very-heavy': 38 },
  },
  {
    id: 'make',
    name: 'Make',
    description: 'Excellent for visual multi-step workflows, routers, transformations, and a broad SaaS estate without making developers the only people who can maintain it.',
    billingModel: 'module-credits',
    billingLabel: 'Most module actions consume credits, so branching, loops, polling, and high record counts matter to usage economics.',
    procurement: 'self-serve',
    technicalDepth: 54,
    technicalRequirement: 42,
    simpleWorkflowFit: 84,
    complexWorkflowFit: 92,
    standardIntegrationBreadth: 94,
    customApiFit: 86,
    scaleFit: 84,
    reliabilityFit: 80,
    governanceFit: 78,
    selfHostFit: 0,
    crmNativeFit: 64,
    microsoftFit: 72,
    costAtScaleFit: 80,
    budgetFloor: 1,
    teamFit: { business: 76, automation: 100, developer: 82, mixed: 92 },
    categoryFit: { ...broad, data: 90, developer: 84, ai: 90, erp: 72 },
    volumeEconomics: { light: 90, moderate: 90, heavy: 82, 'very-heavy': 68 },
  },
  {
    id: 'n8n-cloud',
    name: 'n8n Cloud',
    description: 'Technical orchestration with managed hosting: strong for APIs, reusable logic, data shaping, AI, and workflows where paying per whole execution is attractive.',
    billingModel: 'workflow-executions',
    billingLabel: 'Cloud plans meter whole workflow executions rather than every individual step; concurrency and plan execution allowances still matter.',
    procurement: 'self-serve',
    technicalDepth: 80,
    technicalRequirement: 68,
    simpleWorkflowFit: 58,
    complexWorkflowFit: 98,
    standardIntegrationBreadth: 86,
    customApiFit: 100,
    scaleFit: 92,
    reliabilityFit: 88,
    governanceFit: 84,
    selfHostFit: 0,
    crmNativeFit: 58,
    microsoftFit: 68,
    costAtScaleFit: 90,
    budgetFloor: 1,
    teamFit: { business: 44, automation: 100, developer: 96, mixed: 90 },
    categoryFit: { ...broad, data: 98, developer: 98, ai: 98, erp: 82, automation: 88 },
    volumeEconomics: { light: 70, moderate: 90, heavy: 94, 'very-heavy': 84 },
  },
  {
    id: 'n8n-self-hosted',
    name: 'n8n Self-hosted',
    description: 'Deep orchestration and infrastructure control when a capable technical owner can operate the runtime, upgrades, monitoring, credentials, and recovery.',
    billingModel: 'self-hosted',
    billingLabel: 'Infrastructure can remove some managed-platform usage pressure, but runtime ownership, observability, upgrades, backups, and engineering time become part of total cost.',
    procurement: 'mixed',
    technicalDepth: 92,
    technicalRequirement: 86,
    simpleWorkflowFit: 42,
    complexWorkflowFit: 100,
    standardIntegrationBreadth: 86,
    customApiFit: 100,
    scaleFit: 98,
    reliabilityFit: 92,
    governanceFit: 88,
    selfHostFit: 100,
    crmNativeFit: 54,
    microsoftFit: 68,
    costAtScaleFit: 98,
    budgetFloor: 1,
    teamFit: { business: 22, automation: 86, developer: 100, mixed: 88 },
    categoryFit: { ...broad, data: 100, developer: 100, ai: 100, erp: 86, automation: 92 },
    volumeEconomics: { light: 45, moderate: 78, heavy: 98, 'very-heavy': 100 },
  },
  {
    id: 'power-automate',
    name: 'Power Automate',
    description: 'Best when Microsoft 365, Dynamics, Azure, desktop automation, approvals, identity, and enterprise governance are core parts of the environment.',
    billingModel: 'capacity-licensing',
    billingLabel: 'Licensing depends on user/process/capacity context and premium capabilities, so Microsoft environment and governance matter as much as raw run count.',
    procurement: 'mixed',
    technicalDepth: 58,
    technicalRequirement: 42,
    simpleWorkflowFit: 82,
    complexWorkflowFit: 90,
    standardIntegrationBreadth: 84,
    customApiFit: 84,
    scaleFit: 90,
    reliabilityFit: 92,
    governanceFit: 100,
    selfHostFit: 18,
    crmNativeFit: 68,
    microsoftFit: 100,
    costAtScaleFit: 78,
    budgetFloor: 2,
    teamFit: { business: 82, automation: 96, developer: 88, mixed: 96 },
    categoryFit: { ...broad, crm: 92, communication: 100, project: 94, data: 94, documents: 100, erp: 92, developer: 88 },
    volumeEconomics: { light: 74, moderate: 84, heavy: 88, 'very-heavy': 88 },
  },
  {
    id: 'activepieces',
    name: 'Activepieces',
    description: 'Open-source-friendly automation with cloud and self-hosting options; most compelling when ownership/control matters and required connectors are available.',
    billingModel: 'workflow-executions',
    billingLabel: 'Run-based economics can be attractive, but connector depth and the operational cost of self-hosting need to be checked for the actual stack.',
    procurement: 'self-serve',
    technicalDepth: 70,
    technicalRequirement: 58,
    simpleWorkflowFit: 68,
    complexWorkflowFit: 86,
    standardIntegrationBreadth: 70,
    customApiFit: 92,
    scaleFit: 88,
    reliabilityFit: 82,
    governanceFit: 74,
    selfHostFit: 100,
    crmNativeFit: 52,
    microsoftFit: 58,
    costAtScaleFit: 94,
    budgetFloor: 0,
    teamFit: { business: 50, automation: 92, developer: 94, mixed: 84 },
    categoryFit: { ...broad, crm: 76, marketing: 76, finance: 70, hr: 62, erp: 58, developer: 92, data: 92 },
    volumeEconomics: { light: 80, moderate: 92, heavy: 96, 'very-heavy': 96 },
  },
  {
    id: 'pipedream',
    name: 'Pipedream',
    description: 'Developer-oriented workflows and integrations where code, APIs, event handling, and compute-based execution are more natural than a pure no-code canvas.',
    billingModel: 'compute-credits',
    billingLabel: 'Workflow usage is compute-credit based rather than step-count based, so runtime, memory, and control-flow segments matter more than raw action count.',
    procurement: 'self-serve',
    technicalDepth: 88,
    technicalRequirement: 82,
    simpleWorkflowFit: 52,
    complexWorkflowFit: 96,
    standardIntegrationBreadth: 90,
    customApiFit: 100,
    scaleFit: 94,
    reliabilityFit: 88,
    governanceFit: 78,
    selfHostFit: 0,
    crmNativeFit: 48,
    microsoftFit: 62,
    costAtScaleFit: 90,
    budgetFloor: 1,
    teamFit: { business: 24, automation: 76, developer: 100, mixed: 82 },
    categoryFit: { ...broad, developer: 100, data: 98, ai: 98, erp: 82, crm: 82 },
    volumeEconomics: { light: 72, moderate: 90, heavy: 94, 'very-heavy': 92 },
  },
  {
    id: 'workato',
    name: 'Workato',
    description: 'Enterprise integration and orchestration for larger automation programs that need governance, collaboration, lifecycle controls, and broad business-system connectivity.',
    billingModel: 'enterprise-usage',
    billingLabel: 'Usage-based enterprise pricing combines platform capability with consumption; it becomes relevant when governance and portfolio scale justify the procurement overhead.',
    procurement: 'enterprise',
    technicalDepth: 68,
    technicalRequirement: 56,
    simpleWorkflowFit: 70,
    complexWorkflowFit: 96,
    standardIntegrationBreadth: 96,
    customApiFit: 94,
    scaleFit: 100,
    reliabilityFit: 96,
    governanceFit: 100,
    selfHostFit: 20,
    crmNativeFit: 70,
    microsoftFit: 90,
    costAtScaleFit: 80,
    budgetFloor: 4,
    teamFit: { business: 68, automation: 98, developer: 90, mixed: 100 },
    categoryFit: { ...broad, erp: 100, hr: 98, finance: 98, data: 96, developer: 90 },
    volumeEconomics: { light: 42, moderate: 68, heavy: 92, 'very-heavy': 98 },
  },
  {
    id: 'tray',
    name: 'Tray.ai',
    description: 'Enterprise-grade composable integration when a larger team needs reusable services, governance, APIs, and cross-department orchestration.',
    billingModel: 'enterprise-usage',
    billingLabel: 'Best treated as enterprise platform economics rather than a small-team subscription; portfolio scale and governance need to justify it.',
    procurement: 'enterprise',
    technicalDepth: 76,
    technicalRequirement: 64,
    simpleWorkflowFit: 58,
    complexWorkflowFit: 96,
    standardIntegrationBreadth: 92,
    customApiFit: 98,
    scaleFit: 100,
    reliabilityFit: 96,
    governanceFit: 98,
    selfHostFit: 0,
    crmNativeFit: 62,
    microsoftFit: 82,
    costAtScaleFit: 78,
    budgetFloor: 4,
    teamFit: { business: 52, automation: 98, developer: 96, mixed: 98 },
    categoryFit: { ...broad, erp: 96, data: 98, developer: 98, finance: 94 },
    volumeEconomics: { light: 35, moderate: 62, heavy: 92, 'very-heavy': 98 },
  },
  {
    id: 'mulesoft',
    name: 'MuleSoft',
    description: 'Enterprise integration and API management for organizations whose problem is broader than workflow automation and includes governed APIs, legacy systems, and integration architecture.',
    billingModel: 'enterprise-usage',
    billingLabel: 'Enterprise platform economics and implementation effort are substantial; it only makes sense when API/integration architecture is itself a strategic capability.',
    procurement: 'enterprise',
    technicalDepth: 92,
    technicalRequirement: 88,
    simpleWorkflowFit: 24,
    complexWorkflowFit: 100,
    standardIntegrationBreadth: 92,
    customApiFit: 100,
    scaleFit: 100,
    reliabilityFit: 100,
    governanceFit: 100,
    selfHostFit: 78,
    crmNativeFit: 58,
    microsoftFit: 88,
    costAtScaleFit: 66,
    budgetFloor: 5,
    teamFit: { business: 12, automation: 66, developer: 100, mixed: 84 },
    categoryFit: { ...broad, erp: 100, data: 100, developer: 100, finance: 98, hr: 96 },
    volumeEconomics: { light: 12, moderate: 38, heavy: 82, 'very-heavy': 100 },
  },
  {
    id: 'custom-code',
    name: 'Custom application / code',
    description: 'Use software rather than a giant workflow when the core becomes stateful, transactional, customer-facing, latency-sensitive, or requires a bespoke interface and domain model.',
    billingModel: 'engineering',
    billingLabel: 'Usage fees become infrastructure costs, but engineering, testing, observability, maintenance, and on-call ownership dominate total cost.',
    procurement: 'engineering',
    technicalDepth: 100,
    technicalRequirement: 100,
    simpleWorkflowFit: 12,
    complexWorkflowFit: 100,
    standardIntegrationBreadth: 100,
    customApiFit: 100,
    scaleFit: 100,
    reliabilityFit: 100,
    governanceFit: 96,
    selfHostFit: 100,
    crmNativeFit: 36,
    microsoftFit: 88,
    costAtScaleFit: 74,
    budgetFloor: 4,
    teamFit: { business: 8, automation: 44, developer: 100, mixed: 76 },
    categoryFit: { crm: 98, marketing: 98, forms: 98, communication: 98, project: 98, finance: 100, commerce: 100, data: 100, developer: 100, support: 98, ads: 96, web: 100, ai: 100, hr: 98, calendar: 98, documents: 98, automation: 100, erp: 100 },
    volumeEconomics: { light: 18, moderate: 42, heavy: 78, 'very-heavy': 96 },
  },
]
