import type { AssessmentInput } from './types'

export const DEFAULT_ASSESSMENT: AssessmentInput = {
  selectedApps: [],
  customSystems: [],
  otherSystemsCount: 0,
  unknownSystemsRequireApi: false,
  primarySystemId: null,
  currentWorkflows: 5,
  futureWorkflows: 12,
  monthlyRuns: 2500,
  departments: 1,
  portfolioShape: 'mixed',
  technicalOwner: 'power-user',
  budget: '100-300',
  changeFrequency: 'monthly',
  appsPerWorkflow: 4,
  typicalSteps: 7,
  team: 'business',
  maintenance: 'medium',
  processStability: 'stable',
  integrationNeed: 'standard',
  branching: 'simple',
  loopsOrBatching: false,
  humanApprovals: false,
  customApi: false,
  aiSteps: false,
  filesOrDocuments: false,
  databaseWork: false,
  realtime: false,
  crmCentered: false,
  microsoftFirst: false,
  failureImpact: 'medium',
  duplicateUnsafe: false,
  retriesRequired: false,
  sensitiveData: false,
  selfHosting: 'none',
  governance: false,
  productLogic: false,
  priorities: ['ease', 'speed'],
}

export const BENCHMARK_SCENARIOS: Array<{ name: string; input: AssessmentInput; expectedPrimary: string }> = [
  {
    name: 'simple HubSpot follow-up',
    expectedPrimary: 'crm-native',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['hubspot', 'slack'],
      primarySystemId: 'hubspot',
      currentWorkflows: 3,
      futureWorkflows: 6,
      appsPerWorkflow: 2,
      typicalSteps: 4,
      portfolioShape: 'mostly-simple',
      crmCentered: true,
      branching: 'none',
      monthlyRuns: 1200,
      technicalOwner: 'none',
      maintenance: 'low',
    },
  },
  {
    name: 'non-technical SaaS handoffs',
    expectedPrimary: 'zapier',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['hubspot', 'typeform', 'slack', 'google-sheets', 'calendly'],
      primarySystemId: 'hubspot',
      currentWorkflows: 8,
      futureWorkflows: 16,
      appsPerWorkflow: 4,
      typicalSteps: 5,
      integrationNeed: 'broad',
      technicalOwner: 'none',
      team: 'business',
      maintenance: 'low',
      portfolioShape: 'mostly-simple',
      branching: 'simple',
    },
  },
  {
    name: 'visual multi-step operations',
    expectedPrimary: 'make',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['shopify', 'airtable', 'slack', 'quickbooks', 'shipstation', 'google-sheets'],
      currentWorkflows: 12,
      futureWorkflows: 25,
      appsPerWorkflow: 6,
      typicalSteps: 12,
      technicalOwner: 'automation-specialist',
      team: 'automation',
      maintenance: 'medium',
      portfolioShape: 'mixed',
      branching: 'advanced',
      loopsOrBatching: true,
      integrationNeed: 'broad',
    },
  },
  {
    name: 'API-heavy managed orchestration',
    expectedPrimary: 'n8n-cloud',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['hubspot', 'openai', 'postgresql', 'slack', 'github'],
      customSystems: ['Internal enrichment API'],
      otherSystemsCount: 1,
      unknownSystemsRequireApi: true,
      currentWorkflows: 20,
      futureWorkflows: 55,
      appsPerWorkflow: 7,
      typicalSteps: 18,
      technicalOwner: 'automation-specialist',
      team: 'automation',
      maintenance: 'high',
      portfolioShape: 'advanced',
      branching: 'advanced',
      customApi: true,
      aiSteps: true,
      databaseWork: true,
      monthlyRuns: 35000,
      budget: '300-1000',
      priorities: ['scale', 'control', 'cost'],
    },
  },
  {
    name: 'Microsoft governed environment',
    expectedPrimary: 'power-automate',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['dynamics-365', 'microsoft-teams', 'sharepoint', 'onedrive', 'excel', 'outlook'],
      primarySystemId: 'dynamics-365',
      currentWorkflows: 20,
      futureWorkflows: 70,
      departments: 4,
      appsPerWorkflow: 5,
      typicalSteps: 10,
      technicalOwner: 'automation-specialist',
      team: 'mixed',
      maintenance: 'medium',
      microsoftFirst: true,
      governance: true,
      humanApprovals: true,
      budget: '1000-5000',
      priorities: ['reliability', 'ease'],
    },
  },
  {
    name: 'self-hosted technical orchestration',
    expectedPrimary: 'n8n-self-hosted',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['postgresql', 'openai', 'github', 'slack', 'hubspot'],
      currentWorkflows: 12,
      futureWorkflows: 35,
      appsPerWorkflow: 6,
      typicalSteps: 14,
      technicalOwner: 'developer',
      team: 'developer',
      maintenance: 'high',
      portfolioShape: 'advanced',
      customApi: true,
      selfHosting: 'required',
      branching: 'advanced',
      budget: '300-1000',
      priorities: ['control', 'scale'],
    },
  },
  {
    name: 'developer event and API workflows',
    expectedPrimary: 'pipedream',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['github', 'vercel', 'stripe', 'openai', 'postgresql'],
      currentWorkflows: 8,
      futureWorkflows: 18,
      monthlyRuns: 15000,
      appsPerWorkflow: 5,
      typicalSteps: 10,
      technicalOwner: 'developer',
      team: 'developer',
      maintenance: 'high',
      portfolioShape: 'advanced',
      customApi: true,
      realtime: true,
      branching: 'simple',
      budget: '100-300',
      priorities: ['control', 'speed'],
    },
  },
  {
    name: 'stateful product logic',
    expectedPrimary: 'custom-code',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['stripe', 'postgresql', 'redis', 'github', 'sentry', 'openai'],
      currentWorkflows: 4,
      futureWorkflows: 10,
      appsPerWorkflow: 8,
      typicalSteps: 24,
      technicalOwner: 'developer',
      team: 'developer',
      maintenance: 'high',
      portfolioShape: 'product-like',
      customApi: true,
      databaseWork: true,
      realtime: true,
      productLogic: true,
      failureImpact: 'critical',
      duplicateUnsafe: true,
      retriesRequired: true,
      budget: '1000-5000',
      priorities: ['reliability', 'control', 'scale'],
    },
  },
]
