import type { AssessmentInput, PlatformId } from './types'

export const DEFAULT_ASSESSMENT: AssessmentInput = {
  selectedApps: [],
  customSystems: [],
  otherSystemsCount: 0,
  unknownSystemsRequireApi: false,
  primarySystemId: null,
  currentWorkflows: 5,
  futureWorkflows: 12,
  monthlyRuns: 2500,
  departments: 1,
  portfolioShape: 'mixed',
  technicalOwner: 'power-user',
  budget: '100-300',
  changeFrequency: 'monthly',
  appsPerWorkflow: 4,
  typicalSteps: 7,
  team: 'business',
  maintenance: 'medium',
  processStability: 'stable',
  integrationNeed: 'standard',
  branching: 'simple',
  loopsOrBatching: false,
  durableJobs: false,
  humanApprovals: false,
  customApi: false,
  aiSteps: false,
  filesOrDocuments: false,
  databaseWork: false,
  realtime: false,
  crmCentered: false,
  microsoftFirst: false,
  failureImpact: 'medium',
  duplicateUnsafe: false,
  retriesRequired: false,
  sensitiveData: false,
  selfHosting: 'none',
  governance: false,
  productLogic: false,
  priorities: ['ease', 'speed'],
}

export const BENCHMARK_SCENARIOS: Array<{ name: string; input: AssessmentInput; expectedPrimary: PlatformId }> = [
  {
    name: 'simple HubSpot follow-up',
    expectedPrimary: 'hubspot-native',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['hubspot', 'slack'],
      primarySystemId: 'hubspot',
      currentWorkflows: 3,
      futureWorkflows: 6,
      appsPerWorkflow: 2,
      typicalSteps: 4,
      portfolioShape: 'mostly-simple',
      crmCentered: true,
      branching: 'none',
      monthlyRuns: 1200,
      technicalOwner: 'none',
      maintenance: 'low',
    },
  },
  {
    name: 'GoHighLevel lead and follow-up engine',
    expectedPrimary: 'gohighlevel-native',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['gohighlevel', 'facebook-leads', 'stripe', 'google-calendar'],
      primarySystemId: 'gohighlevel',
      currentWorkflows: 8,
      futureWorkflows: 18,
      monthlyRuns: 6000,
      appsPerWorkflow: 3,
      typicalSteps: 7,
      portfolioShape: 'mostly-simple',
      crmCentered: true,
      technicalOwner: 'power-user',
      team: 'business',
      maintenance: 'medium',
      branching: 'simple',
      priorities: ['ease', 'speed', 'cost'],
    },
  },
  {
    name: 'simple Zoho CRM native work',
    expectedPrimary: 'crm-native',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['zoho-crm', 'slack'],
      primarySystemId: 'zoho-crm',
      currentWorkflows: 4,
      futureWorkflows: 8,
      appsPerWorkflow: 2,
      typicalSteps: 4,
      portfolioShape: 'mostly-simple',
      crmCentered: true,
      branching: 'none',
      technicalOwner: 'none',
      maintenance: 'low',
    },
  },
  {
    name: 'Salesforce governed CRM process',
    expectedPrimary: 'salesforce-flow',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['salesforce', 'slack', 'docusign'],
      primarySystemId: 'salesforce',
      currentWorkflows: 24,
      futureWorkflows: 55,
      departments: 3,
      appsPerWorkflow: 3,
      typicalSteps: 8,
      portfolioShape: 'mixed',
      technicalOwner: 'automation-specialist',
      team: 'mixed',
      maintenance: 'high',
      governance: true,
      sensitiveData: true,
      budget: '1000-5000',
      priorities: ['reliability', 'ease'],
    },
  },
  {
    name: 'Shopify store operations',
    expectedPrimary: 'shopify-flow',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['shopify', 'klaviyo', 'gorgias', 'shipstation'],
      currentWorkflows: 8,
      futureWorkflows: 15,
      monthlyRuns: 7000,
      appsPerWorkflow: 3,
      typicalSteps: 5,
      portfolioShape: 'mostly-simple',
      technicalOwner: 'power-user',
      team: 'business',
      maintenance: 'low',
      branching: 'simple',
      priorities: ['ease', 'cost'],
    },
  },
  {
    name: 'non-technical SaaS handoffs',
    expectedPrimary: 'zapier',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['hubspot', 'typeform', 'slack', 'google-sheets', 'calendly'],
      primarySystemId: 'hubspot',
      currentWorkflows: 8,
      futureWorkflows: 16,
      appsPerWorkflow: 4,
      typicalSteps: 5,
      integrationNeed: 'broad',
      technicalOwner: 'none',
      team: 'business',
      maintenance: 'low',
      portfolioShape: 'mostly-simple',
      crmCentered: false,
      branching: 'simple',
    },
  },
  {
    name: 'visual multi-step operations',
    expectedPrimary: 'make',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['shopify', 'airtable', 'slack', 'quickbooks', 'shipstation', 'google-sheets'],
      currentWorkflows: 12,
      futureWorkflows: 25,
      appsPerWorkflow: 6,
      typicalSteps: 12,
      technicalOwner: 'automation-specialist',
      team: 'automation',
      maintenance: 'medium',
      portfolioShape: 'mixed',
      branching: 'advanced',
      loopsOrBatching: true,
      integrationNeed: 'broad',
    },
  },
  {
    name: 'API-heavy managed orchestration',
    expectedPrimary: 'n8n-cloud',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['hubspot', 'openai', 'postgresql', 'slack', 'github'],
      customSystems: ['Internal enrichment API'],
      otherSystemsCount: 1,
      unknownSystemsRequireApi: true,
      currentWorkflows: 20,
      futureWorkflows: 55,
      appsPerWorkflow: 7,
      typicalSteps: 18,
      technicalOwner: 'automation-specialist',
      team: 'automation',
      maintenance: 'high',
      portfolioShape: 'advanced',
      branching: 'advanced',
      customApi: true,
      aiSteps: true,
      databaseWork: true,
      monthlyRuns: 35000,
      budget: '300-1000',
      priorities: ['scale', 'control', 'cost'],
    },
  },
  {
    name: 'Microsoft governed environment',
    expectedPrimary: 'power-automate',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['dynamics-365', 'microsoft-teams', 'sharepoint', 'onedrive', 'excel', 'outlook'],
      primarySystemId: 'dynamics-365',
      currentWorkflows: 20,
      futureWorkflows: 70,
      departments: 4,
      appsPerWorkflow: 5,
      typicalSteps: 10,
      technicalOwner: 'automation-specialist',
      team: 'mixed',
      maintenance: 'medium',
      microsoftFirst: true,
      governance: true,
      humanApprovals: true,
      budget: '1000-5000',
      priorities: ['reliability', 'ease'],
    },
  },
  {
    name: 'self-hosted technical orchestration',
    expectedPrimary: 'n8n-self-hosted',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['postgresql', 'openai', 'github', 'slack', 'hubspot'],
      currentWorkflows: 12,
      futureWorkflows: 35,
      appsPerWorkflow: 6,
      typicalSteps: 14,
      technicalOwner: 'developer',
      team: 'developer',
      maintenance: 'high',
      portfolioShape: 'advanced',
      customApi: true,
      selfHosting: 'required',
      branching: 'advanced',
      budget: '300-1000',
      priorities: ['control', 'scale'],
    },
  },
  {
    name: 'self-hosted visual automation team',
    expectedPrimary: 'activepieces',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['google-sheets', 'slack', 'hubspot', 'openai'],
      currentWorkflows: 10,
      futureWorkflows: 25,
      monthlyRuns: 18000,
      appsPerWorkflow: 4,
      typicalSteps: 8,
      technicalOwner: 'automation-specialist',
      team: 'automation',
      maintenance: 'medium',
      portfolioShape: 'mixed',
      branching: 'simple',
      selfHosting: 'required',
      customApi: false,
      budget: '100-300',
      priorities: ['control', 'cost', 'ease'],
    },
  },
  {
    name: 'developer event and API workflows',
    expectedPrimary: 'pipedream',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['github', 'vercel', 'stripe', 'openai'],
      currentWorkflows: 6,
      futureWorkflows: 14,
      monthlyRuns: 10000,
      appsPerWorkflow: 3,
      typicalSteps: 4,
      technicalOwner: 'developer',
      team: 'developer',
      maintenance: 'high',
      portfolioShape: 'mostly-simple',
      customApi: true,
      realtime: true,
      branching: 'none',
      budget: '100-300',
      priorities: ['control', 'speed'],
    },
  },
  {
    name: 'durable TypeScript background jobs',
    expectedPrimary: 'trigger-dev',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['github', 'vercel', 'openai', 'stripe', 'postgresql', 'sentry'],
      currentWorkflows: 8,
      futureWorkflows: 20,
      monthlyRuns: 25000,
      appsPerWorkflow: 4,
      typicalSteps: 10,
      technicalOwner: 'developer',
      team: 'developer',
      maintenance: 'high',
      portfolioShape: 'advanced',
      customApi: true,
      durableJobs: true,
      aiSteps: true,
      databaseWork: true,
      realtime: true,
      retriesRequired: true,
      failureImpact: 'high',
      budget: '300-1000',
      priorities: ['reliability', 'control', 'scale'],
    },
  },
  {
    name: 'enterprise business automation program',
    expectedPrimary: 'workato',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['salesforce', 'netsuite', 'workday', 'sap', 'snowflake', 'jira'],
      primarySystemId: 'salesforce',
      currentWorkflows: 70,
      futureWorkflows: 150,
      monthlyRuns: 250000,
      departments: 6,
      appsPerWorkflow: 6,
      typicalSteps: 12,
      technicalOwner: 'automation-specialist',
      team: 'mixed',
      maintenance: 'high',
      portfolioShape: 'advanced',
      branching: 'advanced',
      governance: true,
      sensitiveData: true,
      humanApprovals: true,
      budget: 'flexible',
      priorities: ['reliability', 'scale', 'ease'],
    },
  },
  {
    name: 'enterprise composable API integration',
    expectedPrimary: 'tray',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['salesforce', 'snowflake', 'postgresql', 'stripe', 'github', 'netsuite'],
      primarySystemId: 'salesforce',
      currentWorkflows: 55,
      futureWorkflows: 120,
      monthlyRuns: 300000,
      departments: 5,
      appsPerWorkflow: 7,
      typicalSteps: 16,
      technicalOwner: 'developer',
      team: 'developer',
      maintenance: 'high',
      portfolioShape: 'advanced',
      branching: 'advanced',
      customApi: true,
      governance: true,
      budget: 'flexible',
      priorities: ['control', 'scale', 'reliability'],
    },
  },
  {
    name: 'enterprise API and legacy architecture',
    expectedPrimary: 'mulesoft',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['salesforce', 'sap', 'netsuite', 'workday', 'aws', 'snowflake'],
      primarySystemId: 'salesforce',
      customSystems: ['Legacy ERP gateway', 'Partner API estate'],
      otherSystemsCount: 7,
      unknownSystemsRequireApi: true,
      currentWorkflows: 120,
      futureWorkflows: 260,
      monthlyRuns: 800000,
      departments: 7,
      appsPerWorkflow: 10,
      typicalSteps: 24,
      technicalOwner: 'developer',
      team: 'developer',
      maintenance: 'high',
      portfolioShape: 'advanced',
      branching: 'advanced',
      customApi: true,
      governance: true,
      sensitiveData: true,
      budget: 'flexible',
      priorities: ['reliability', 'control', 'scale'],
    },
  },
  {
    name: 'stateful product logic',
    expectedPrimary: 'custom-code',
    input: {
      ...DEFAULT_ASSESSMENT,
      selectedApps: ['stripe', 'postgresql', 'redis', 'github', 'sentry', 'openai'],
      currentWorkflows: 4,
      futureWorkflows: 10,
      appsPerWorkflow: 8,
      typicalSteps: 24,
      technicalOwner: 'developer',
      team: 'developer',
      maintenance: 'high',
      portfolioShape: 'product-like',
      customApi: true,
      databaseWork: true,
      realtime: true,
      productLogic: true,
      failureImpact: 'critical',
      duplicateUnsafe: true,
      retriesRequired: true,
      budget: '1000-5000',
      priorities: ['reliability', 'control', 'scale'],
    },
  },
]
