'use client'

import { useMemo, useState } from 'react'
import { ArrowLeftIcon, ArrowRightIcon, CheckIcon, RotateCcwIcon, SearchIcon } from 'lucide-react'

import { APP_BY_ID, APP_CATALOG, type AppDefinition } from '@/engine/apps'
import type { BranchingNeed, FailureImpact, ProcessStability, SelfHostingNeed, TeamProfile, TechnicalOwner } from '@/engine/types'
import {
  analyzeWorkflowBlueprint,
  DEFAULT_WORKFLOW_BLUEPRINT_INPUT,
  type TransformationNeed,
  type WorkflowBlueprintInput,
  type WorkflowTriggerMode,
} from '@/engine/workflow-blueprint'

type PageId = 'systems' | 'logic' | 'reliability' | 'result'
const pages: PageId[] = ['systems', 'logic', 'reliability', 'result']

function AppIcon({ app }: { app: AppDefinition }) {
  if (!app.icon) return <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-zinc-100 text-[10px] font-semibold text-zinc-600 dark:bg-zinc-900 dark:text-zinc-300">{app.name.slice(0, 2).toUpperCase()}</span>
  return <span aria-hidden="true" className="h-8 w-8 shrink-0 rounded-md bg-zinc-100 bg-[length:66%] bg-center bg-no-repeat dark:bg-zinc-900" style={{ backgroundImage: `url(https://cdn.simpleicons.org/${app.icon})` }} />
}

function Select({ value, onChange, children }: { value: string | number; onChange: (value: string) => void; children: React.ReactNode }) {
  return <select value={value} onChange={(event) => onChange(event.target.value)} className="min-h-12 w-full rounded-lg border border-zinc-300 bg-white px-3.5 py-2.5 text-sm font-medium text-zinc-950 outline-none focus:border-zinc-950 dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-50 dark:focus:border-zinc-100">{children}</select>
}

function Field({ label, helper, children }: { label: string; helper?: string; children: React.ReactNode }) {
  return <div className="grid gap-3 py-4 sm:grid-cols-[210px_1fr] sm:gap-7"><div><p className="text-[15px] font-medium leading-6 text-zinc-950 dark:text-zinc-50">{label}</p>{helper ? <p className="mt-1 max-w-[220px] text-[13px] leading-5 text-zinc-500 dark:text-zinc-400">{helper}</p> : null}</div><div className="self-center">{children}</div></div>
}

function Toggle({ checked, onChange, title, description }: { checked: boolean; onChange: (checked: boolean) => void; title: string; description?: string }) {
  return <button type="button" onClick={() => onChange(!checked)} className={`flex min-h-14 w-full items-start gap-3 rounded-lg px-3.5 py-3 text-left transition-colors ${checked ? 'bg-zinc-950 text-white dark:bg-zinc-50 dark:text-zinc-950' : 'bg-zinc-100 text-zinc-800 hover:bg-zinc-200 dark:bg-zinc-900 dark:text-zinc-200 dark:hover:bg-zinc-800'}`}><span className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-md ${checked ? 'bg-white/15 dark:bg-zinc-950/10' : 'bg-white dark:bg-zinc-800'}`}>{checked ? <CheckIcon className="h-3.5 w-3.5" /> : null}</span><span><span className="block text-sm font-medium">{title}</span>{description ? <span className={`mt-1 block text-xs leading-5 ${checked ? 'text-zinc-300 dark:text-zinc-600' : 'text-zinc-500'}`}>{description}</span> : null}</span></button>
}

function AppSearch({ selected, onSelect, multi = false, placeholder = 'Search apps and systems' }: { selected: string[]; onSelect: (id: string) => void; multi?: boolean; placeholder?: string }) {
  const [query, setQuery] = useState('')
  const results = useMemo(() => {
    const normalized = query.trim().toLowerCase()
    const filtered = normalized ? APP_CATALOG.filter((app) => `${app.name} ${app.vendor} ${app.category}`.toLowerCase().includes(normalized)) : APP_CATALOG
    return filtered.slice(0, multi ? 18 : 14)
  }, [query, multi])

  return <div><label className="flex min-h-11 items-center gap-2 rounded-lg border border-zinc-300 px-3 dark:border-zinc-700"><SearchIcon className="h-4 w-4 shrink-0 text-zinc-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent text-sm text-zinc-950 outline-none placeholder:text-zinc-400 dark:text-zinc-50" /></label><div className="mt-3 grid gap-2 sm:grid-cols-2">{results.map((app) => { const active = selected.includes(app.id); return <button key={app.id} type="button" onClick={() => onSelect(app.id)} className={`flex min-h-13 items-center gap-3 rounded-lg px-3 py-2 text-left transition-colors ${active ? 'bg-zinc-950 text-white dark:bg-zinc-50 dark:text-zinc-950' : 'bg-zinc-100 text-zinc-800 hover:bg-zinc-200 dark:bg-zinc-900 dark:text-zinc-200 dark:hover:bg-zinc-800'}`}><AppIcon app={app} /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{app.name}</span><span className={`block truncate text-[10px] capitalize ${active ? 'text-zinc-300 dark:text-zinc-600' : 'text-zinc-500'}`}>{app.category.replace('-', ' ')}</span></span>{active ? <CheckIcon className="h-4 w-4 shrink-0" /> : null}</button> })}</div></div>
}

function SystemsForm({ input, update }: { input: WorkflowBlueprintInput; update: <K extends keyof WorkflowBlueprintInput>(key: K, value: WorkflowBlueprintInput[K]) => void }) {
  const selectedContext = [...new Set([input.sourceAppId, ...input.targetAppIds].filter((id): id is string => Boolean(id)))]
  const toggleTarget = (id: string) => update('targetAppIds', input.targetAppIds.includes(id) ? input.targetAppIds.filter((item) => item !== id) : [...input.targetAppIds, id])

  return <div className="space-y-6"><header><p className="text-sm font-medium text-zinc-950 dark:text-zinc-50">Start with the real workflow boundary.</p><h2 className="mt-2 text-2xl font-medium tracking-[-0.035em] text-zinc-950 sm:text-3xl dark:text-zinc-50">What event starts the work, and where should the result live?</h2><p className="mt-3 text-[15px] leading-7 text-zinc-600 dark:text-zinc-400">Choosing apps first lets the blueprint reason about native automation, connector depth, APIs and source-of-truth ownership before asking technical questions.</p></header>
    <Field label="Trigger / source system" helper="The system that emits the business event."><AppSearch selected={input.sourceAppId ? [input.sourceAppId] : []} onSelect={(id) => update('sourceAppId', id)} placeholder="Search the trigger app" /></Field>
    <Field label="Destination systems" helper="Select every system this one workflow must read/write or notify."><AppSearch selected={input.targetAppIds} onSelect={toggleTarget} multi placeholder="Search destination apps" /></Field>
    <Field label="Source of truth" helper="When systems disagree, which record/state wins?"><div className="grid gap-2 sm:grid-cols-2">{selectedContext.length ? selectedContext.map((id) => { const app = APP_BY_ID[id]; if (!app) return null; return <button key={id} type="button" onClick={() => update('sourceOfTruthAppId', id)} className={`flex min-h-12 items-center gap-3 rounded-lg px-3 text-left ${input.sourceOfTruthAppId === id ? 'bg-zinc-950 text-white dark:bg-zinc-50 dark:text-zinc-950' : 'bg-zinc-100 text-zinc-800 dark:bg-zinc-900 dark:text-zinc-200'}`}><AppIcon app={app} /><span className="min-w-0 flex-1 truncate text-sm font-medium">{app.name}</span>{input.sourceOfTruthAppId === id ? <CheckIcon className="h-4 w-4" /> : null}</button> }) : <p className="text-sm leading-6 text-zinc-500">Select the source/destination systems first.</p>}</div></Field>
    <Field label="Custom / internal systems" helper="Add names for APIs or systems not in the catalog."><input value={input.customSystems.join(', ')} onChange={(event) => update('customSystems', event.target.value.split(',').map((item) => item.trim()).filter(Boolean))} placeholder="Internal API, legacy ERP" className="min-h-12 w-full rounded-lg border border-zinc-300 bg-transparent px-3.5 text-sm text-zinc-950 outline-none focus:border-zinc-950 dark:border-zinc-700 dark:text-zinc-50" /></Field>
    <Field label="Trigger mode"><Select value={input.triggerMode} onChange={(value) => update('triggerMode', value as WorkflowTriggerMode)}><option value="webhook">Webhook</option><option value="event">Native event / instant trigger</option><option value="polling">Polling for new/updated records</option><option value="schedule">Scheduled query</option><option value="batch">Batch/import</option><option value="manual">Manual approval/start</option></Select></Field>
  </div>
}

function LogicForm({ input, update }: { input: WorkflowBlueprintInput; update: <K extends keyof WorkflowBlueprintInput>(key: K, value: WorkflowBlueprintInput[K]) => void }) {
  return <div className="space-y-6"><header><p className="text-sm font-medium text-zinc-950 dark:text-zinc-50">Now define the shape of the work.</p><h2 className="mt-2 text-2xl font-medium tracking-[-0.035em] text-zinc-950 sm:text-3xl dark:text-zinc-50">Is this a handoff, an orchestration problem, or software?</h2><p className="mt-3 text-[15px] leading-7 text-zinc-600 dark:text-zinc-400">The engine uses complexity and ownership to decide which implementation lane earns its overhead.</p></header>
    <Field label="Typical steps"><Select value={input.steps} onChange={(value) => update('steps', Number(value))}><option value={2}>2–3 steps</option><option value={5}>4–6 steps</option><option value={9}>7–10 steps</option><option value={14}>11–15 steps</option><option value={20}>16+ steps</option></Select></Field>
    <Field label="Branching"><Select value={input.branching} onChange={(value) => update('branching', value as BranchingNeed)}><option value="none">No branching / straight path</option><option value="simple">A few simple conditions</option><option value="advanced">Many overlapping routes / decisions</option></Select></Field>
    <Field label="Data transformation"><Select value={input.transformation} onChange={(value) => update('transformation', value as TransformationNeed)}><option value="light">Map/rename a few fields</option><option value="moderate">Reshape / combine data</option><option value="heavy">Complex transformations / reconciliation</option></Select></Field>
    <div className="grid gap-2 sm:grid-cols-2"><Toggle checked={input.loopsOrBatching} onChange={(value) => update('loopsOrBatching', value)} title="Loops / batches" description="Iterate collections or process many records." /><Toggle checked={input.customApi} onChange={(value) => update('customApi', value)} title="Custom APIs" description="REST/GraphQL/custom authentication or endpoints." /><Toggle checked={input.databaseWork} onChange={(value) => update('databaseWork', value)} title="Database / durable state" description="Read/write persistent state outside ordinary app records." /><Toggle checked={input.filesOrDocuments} onChange={(value) => update('filesOrDocuments', value)} title="Files / documents" description="Large files, generated docs, parsing or storage." /><Toggle checked={input.aiSteps} onChange={(value) => update('aiSteps', value)} title="AI step" description="Classification, extraction, generation or reasoning." /><Toggle checked={input.humanApprovals} onChange={(value) => update('humanApprovals', value)} title="Human approval / wait" description="Pause and resume around a person’s decision." /><Toggle checked={input.durableJobs} onChange={(value) => update('durableJobs', value)} title="Long-running / durable job" description="May wait, retry or run for a long time." /><Toggle checked={input.transactional} onChange={(value) => update('transactional', value)} title="Transactional core" description="Money, inventory, permissions or customer-facing state must stay consistent." /></div>
    <Field label="Process stability"><Select value={input.processStability} onChange={(value) => update('processStability', value as ProcessStability)}><option value="stable">Stable and repeatable</option><option value="mostly-stable">Mostly stable, occasional changes</option><option value="changing">Still changing materially</option></Select></Field>
    <Field label="Maintainer"><div className="grid gap-2 sm:grid-cols-2"><Select value={input.team} onChange={(value) => update('team', value as TeamProfile)}><option value="business">Business operations team</option><option value="automation">Automation / RevOps team</option><option value="developer">Developers</option><option value="mixed">Mixed business + technical team</option></Select><Select value={input.technicalOwner} onChange={(value) => update('technicalOwner', value as TechnicalOwner)}><option value="none">No technical owner</option><option value="power-user">Power user</option><option value="automation-specialist">Automation specialist</option><option value="developer">Developer</option></Select></div></Field>
  </div>
}

function ReliabilityForm({ input, update }: { input: WorkflowBlueprintInput; update: <K extends keyof WorkflowBlueprintInput>(key: K, value: WorkflowBlueprintInput[K]) => void }) {
  return <div className="space-y-6"><header><p className="text-sm font-medium text-zinc-950 dark:text-zinc-50">Then design for production, not the demo.</p><h2 className="mt-2 text-2xl font-medium tracking-[-0.035em] text-zinc-950 sm:text-3xl dark:text-zinc-50">What happens when the event arrives twice, late, or during a burst?</h2><p className="mt-3 text-[15px] leading-7 text-zinc-600 dark:text-zinc-400">Reliability requirements often change the correct platform more than the happy-path diagram does.</p></header>
    <Field label="Monthly runs"><Select value={input.monthlyRuns} onChange={(value) => update('monthlyRuns', Number(value))}><option value={200}>Under 1,000</option><option value={5000}>1,000–15,000</option><option value={50000}>15,000–100,000</option><option value={250000}>100,000+</option></Select></Field>
    <Field label="Peak burst"><Select value={input.peakRunsPerMinute} onChange={(value) => update('peakRunsPerMinute', Number(value))}><option value={2}>A few / minute</option><option value={20}>~20 / minute</option><option value={100}>~100 / minute</option><option value={500}>500+ / minute</option></Select></Field>
    <Field label="Failure impact"><Select value={input.failureImpact} onChange={(value) => update('failureImpact', value as FailureImpact)}><option value="low">Low — easy to replay</option><option value="medium">Medium — visible operational issue</option><option value="high">High — customer/revenue impact</option><option value="critical">Critical — money, access or core operation</option></Select></Field>
    <div className="grid gap-2 sm:grid-cols-2"><Toggle checked={input.duplicateUnsafe} onChange={(value) => update('duplicateUnsafe', value)} title="Duplicate side effects are unsafe" description="A retry could double-create, double-charge, double-message, etc." /><Toggle checked={input.retriesRequired} onChange={(value) => update('retriesRequired', value)} title="Retries required" description="Temporary provider/network failures must recover." /><Toggle checked={input.realtime} onChange={(value) => update('realtime', value)} title="Near-real-time required" description="Minutes of delay materially hurt the outcome." /><Toggle checked={input.writebackRequired} onChange={(value) => update('writebackRequired', value)} title="Write outcome back" description="Humans/future workflows need status and external IDs in the source system." /><Toggle checked={input.sensitiveData} onChange={(value) => update('sensitiveData', value)} title="Sensitive data" description="Credentials, regulated or sensitive customer/business data crosses the flow." /><Toggle checked={input.governance} onChange={(value) => update('governance', value)} title="Governance required" description="Environments, approvals, audit, access control or enterprise change management." /></div>
    <Field label="Hosting / control"><Select value={input.selfHosting} onChange={(value) => update('selfHosting', value as SelfHostingNeed)}><option value="none">Managed cloud is fine</option><option value="preferred">Prefer self-host/control</option><option value="required">Self-hosting is required</option></Select></Field>
  </div>
}

function Result({ input }: { input: WorkflowBlueprintInput }) {
  const result = useMemo(() => analyzeWorkflowBlueprint(input), [input])
  return <div className="space-y-12 pb-8"><header><p className="text-xs font-medium uppercase tracking-[0.12em] text-zinc-500">{result.lane} · {result.confidence}% confidence · complexity {result.complexity}/100</p><h2 className="mt-3 text-3xl font-medium tracking-[-0.045em] text-zinc-950 sm:text-4xl dark:text-zinc-50">{result.laneLabel}</h2><p className="mt-4 text-[15px] leading-7 text-zinc-600 dark:text-zinc-400">{result.summary}</p></header>
    <section><h3 className="text-lg font-medium text-zinc-950 dark:text-zinc-50">Implementation blueprint</h3><div className="mt-5 space-y-3">{result.blueprint.map((step) => <article key={step.id} className="rounded-2xl bg-zinc-100 p-5 dark:bg-zinc-900"><p className="font-mono text-[10px] text-zinc-500">{String(step.order).padStart(2,'0')}</p><h4 className="mt-2 text-sm font-medium text-zinc-950 dark:text-zinc-50">{step.label}</h4><p className="mt-2 text-xs leading-5 text-zinc-500">{step.purpose}</p><p className="mt-3 text-sm leading-6 text-zinc-700 dark:text-zinc-300">{step.implementation}</p><p className="mt-2 text-xs leading-5 text-zinc-500">Failure rule: {step.failureRule}</p></article>)}</div></section>
    <section><h3 className="text-lg font-medium text-zinc-950 dark:text-zinc-50">Platform fit</h3><div className="mt-5 space-y-3">{result.platformFits.filter((platform) => platform.eligible).slice(0,5).map((platform, index) => <article key={platform.id} className="rounded-2xl bg-zinc-100 p-5 dark:bg-zinc-900"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[0.12em] text-zinc-500">#{index + 1} · {platform.verdict.replace('-', ' ')}</p><h4 className="mt-1 text-sm font-medium text-zinc-950 dark:text-zinc-50">{platform.name}</h4></div><span className="font-mono text-xs text-zinc-500">{platform.score}/100</span></div>{platform.reasons.length ? <p className="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">{platform.reasons.join(' ')}</p> : null}{platform.tradeoffs.length ? <p className="mt-2 text-xs leading-5 text-zinc-500">Watch: {platform.tradeoffs.join(' ')}</p> : null}</article>)}</div></section>
    <section className="grid gap-7 sm:grid-cols-2"><div><h3 className="text-base font-medium text-zinc-950 dark:text-zinc-50">Idempotency</h3><p className="mt-3 text-sm leading-7 text-zinc-600 dark:text-zinc-400">{result.idempotencyStrategy}</p></div><div><h3 className="text-base font-medium text-zinc-950 dark:text-zinc-50">Recovery</h3><p className="mt-3 text-sm leading-7 text-zinc-600 dark:text-zinc-400">{result.recoveryStrategy}</p></div></section>
    <section><h3 className="text-lg font-medium text-zinc-950 dark:text-zinc-50">Data contract</h3><div className="mt-4 space-y-2">{result.dataContract.map((item) => <p key={item} className="font-mono text-[11px] leading-6 text-zinc-600 dark:text-zinc-400">{item}</p>)}</div></section>
    <section><h3 className="text-lg font-medium text-zinc-950 dark:text-zinc-50">Pre-launch tests</h3><div className="mt-5 space-y-4">{result.testCases.map((testCase) => <div key={testCase.name}><p className="text-sm font-medium text-zinc-950 dark:text-zinc-50">{testCase.name}</p><p className="mt-1 text-sm leading-6 text-zinc-600 dark:text-zinc-400">{testCase.scenario}</p><p className="mt-1 text-xs leading-5 text-zinc-500">Expected: {testCase.expected}</p></div>)}</div></section>
    <section><h3 className="text-lg font-medium text-zinc-950 dark:text-zinc-50">Observability</h3><div className="mt-4 flex flex-wrap gap-2">{result.observability.map((field) => <span key={field} className="rounded-md bg-zinc-100 px-2.5 py-1.5 font-mono text-[10px] text-zinc-600 dark:bg-zinc-900 dark:text-zinc-400">{field}</span>)}</div></section>
    {result.nextQuestions.length ? <section><h3 className="text-lg font-medium text-zinc-950 dark:text-zinc-50">Questions that could still change the design</h3><div className="mt-4 space-y-3">{result.nextQuestions.map((question) => <p key={question} className="text-sm leading-6 text-zinc-600 dark:text-zinc-400">→ {question}</p>)}</div></section> : null}
  </div>
}

export function WorkflowBlueprintBuilder() {
  const [input, setInput] = useState<WorkflowBlueprintInput>(DEFAULT_WORKFLOW_BLUEPRINT_INPUT)
  const [page, setPage] = useState<PageId>('systems')
  const pageIndex = pages.indexOf(page)
  const progress = ((pageIndex + 1) / pages.length) * 100
  const update = <K extends keyof WorkflowBlueprintInput>(key: K, value: WorkflowBlueprintInput[K]) => setInput((current) => ({ ...current, [key]: value }))
  const previous = () => setPage(pages[Math.max(0, pageIndex - 1)] ?? 'systems')
  const next = () => setPage(pages[Math.min(pages.length - 1, pageIndex + 1)] ?? 'result')
  const reset = () => { setInput(DEFAULT_WORKFLOW_BLUEPRINT_INPUT); setPage('systems') }

  return <div className="blueprint-builder grid h-full min-h-0 grid-rows-[auto_minmax(0,1fr)_auto]"><div className="h-0.5 w-full overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-900"><div className="h-full bg-zinc-950 transition-[width] duration-300 dark:bg-zinc-50" style={{ width: `${progress}%` }} /></div><div className="min-h-0 overflow-y-auto py-6 pr-1 sm:py-8">{page === 'systems' ? <SystemsForm input={input} update={update} /> : page === 'logic' ? <LogicForm input={input} update={update} /> : page === 'reliability' ? <ReliabilityForm input={input} update={update} /> : <Result input={input} />}</div><div className="flex items-center justify-between gap-3 py-3"><button type="button" onClick={page === 'systems' ? reset : previous} className="inline-flex min-h-10 items-center gap-2 text-sm text-zinc-500 transition-colors hover:text-zinc-950 dark:hover:text-zinc-50">{page === 'systems' ? <><RotateCcwIcon className="h-4 w-4" />Reset</> : <><ArrowLeftIcon className="h-4 w-4" />Back</>}</button>{page !== 'result' ? <button type="button" onClick={next} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-zinc-950 px-4 text-sm font-medium text-white dark:bg-zinc-50 dark:text-zinc-950">{page === 'reliability' ? 'Build blueprint' : 'Continue'}<ArrowRightIcon className="h-4 w-4" /></button> : <button type="button" onClick={reset} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-zinc-950 px-4 text-sm font-medium text-white dark:bg-zinc-50 dark:text-zinc-950"><RotateCcwIcon className="h-4 w-4" />Build another</button>}</div></div>
}
